BestRestaurants/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine 
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
    public int CuisineId { get; set; }
    public string Type { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }  
  }
}

BestRestaurants/Models/Restaurant.cs
namespace BestRestaurants.Models
{
  public class Restaurant {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string PricePoint { get; set; }
    public string Location { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;
    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(Cuisine => Cuisine.CuisineId == id);
      // ViewBag here to show all restaurants of same cuisine
      List<Restaurant> allRestaurants = _db.Restaurants.Include(restaurant => restaurant.Cuisine).Where(restaurant => restaurant.CuisineId == id).ToList();
      ViewBag.AllRestaurants = allRestaurants;
      return View(thisCuisine);
    }

  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;
    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      // List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId","Type");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@model BestRestaurants.Models.Cuisine;

<h4>Add a new cuisine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)
  <input type="submit" value="Add a new cuisine" />
}
<p>@Html.ActionLink("Show all categories","Index")</p>
<p>@Html.ActionLink("Back home","Index","Home")</p>

BestRestaurants/Views/Cuisines/Details.cshtml
@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<h2>Cuisine Details:</h2>
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h3>


@if (@ViewBag.AllRestaurants.Count == 0)
{
  <p>There are no restaurants of this cuisine yet.</p>
}
@foreach (Restaurant restaurant in @ViewBag.AllRestaurants)
{
  <li>@Html.ActionLink($"{restaurant.Name}","Details", "Restaurants", new { id = restaurant.RestaurantId})</li>
}

BestRestaurants/Views/Cuisines/Index.cshtml
@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No cuisines have been added yet!</h3>
}

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Type}","Details", new { id = cuisine.CuisineId })</li>
}

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurants/Views/Home/Index.cshtml
<h1>Welcome to the Best Restaurant finder!</h1>
<p>@Html.ActionLink("See all restaurants","Index","Restaurants")</p>
<p>@Html.ActionLink("See all cuisines","Index","Cuisines")</p>

BestRestaurants/Views/Restaurants/Create.cshtml
@model BestRestaurants.Models.Restaurant

<h4>Add a new Restaurant:</h4>

@using (Html.BeginForm())
{

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.PricePoint)
  @Html.TextBoxFor(model => model.PricePoint)
  @Html.LabelFor(model => model.Location)
  @Html.TextBoxFor(model => model.Location)
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

<input type="submit" value="Add new retaurant" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all Restaurants", "Index")</p>

BestRestaurants/Views/Restaurants/Details.cshtml
@model BestRestaurants.Models.Restaurant

<h1> Restaurant Details</h1>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<h3>@Html.DisplayNameFor(model => model.PricePoint): @Html.DisplayFor(model => model.PricePoint)</h3>
<h3>@Html.DisplayNameFor(model => model.Cuisine): @Html.DisplayFor(model => model.Cuisine.Type)</h3>
<h3>@Html.DisplayNameFor(model => model.Location): @Html.DisplayFor(model => model.Location)</h3>

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<h1>Restaurants</h1>

@if (Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
}

@foreach(Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}","Details", new { id = restaurant.RestaurantId }) @restaurant.Cuisine.Type</li>
}

<p>@Html.ActionLink("Add new restaurant","Create")</p>
<p>@Html.ActionLink("Home","Index","Home")</p>